name: Delete branch
on: [push, pull_request]
jobs:
  delete_branches:
    runs-on: ubuntu-latest
    steps:
    - name: Delete pr-* branches
      uses: thong-dipro/action-delete-branch@v1
      with:
        github_token: ${{github.token}}
        prefix: dev
