name: Delete branch
on: [push, pull_request]
jobs:
  build_example:
    runs-on: ubuntu-latest
    steps:
     - name: Delete branch in specific repository with a specific owner
       uses: dawidd6/action-delete-branch@v3
       with:
        github_token: ${{github.token}}
        branches: main
        prefix: Main_Develop
