name: Delete branch
on:
  label:
    types: [created, edited]
permissions: write-all
jobs:
  delete_branches:
    runs-on: ubuntu-latest
    steps:
    - name: Delete all branches exclude
      uses: thong-dipro/action-delete-branch@v4
      with:
        github_token: ${{github.token}}
        exclude: main
