name: Delete branch
on: [push, pull_request]
jobs:
  delete_branches:
    runs-on: ubuntu-latest
    steps:
    - name: Delete all branches exclude
      uses: thong-dipro/action-delete-branch@v4
      with:
        github_token: ${{github.token}}
        exclude: main
