name: Delete branch
on: [push, pull_request]
jobs:
  delete_branches:
    runs-on: ubuntu-latest
    steps:
    - name: Delete pr-* branches
      uses: dawidd6/action-delete-branch@v3
      with:
        github_token: ${{github.token}}
        branches: 13,22,3
        prefix: dev
